name: 'Webform Demo: Application/Evaluation System'
type: module
description: 'Demonstrate how to use the Webform module to build an application/evaluation system.'
package: 'Webform Demo'
core: 8.x
dependencies:
  - 'drupal:block'
  - 'webform:webform'
  - 'webform:webform_node'
